# 钉钉推送相关
dingtalk:
  send_url: https://oapi.dingtalk.com/robot/send
  access_token: ${dingtalk_access_token}
  secret: ${dingtalk_secret}

# 新闻联播
xwlb:
  top_id: TOPC1451528971114112
  home_page: https://tv.cctv.com/lm/xwlb/
  day_url: https://tv.cctv.com/lm/xwlb/day/{}.shtml
  tag_url: https://vdn.apps.cntv.cn/api/getHttpVideoInfo.do?pid={}

# 今日说法
jrsf:
  top_id: TOPC1451464665008914
  home_page: https://tv.cctv.com/lm/jrsf/
  day_url: https://api.cntv.cn/NewVideo/getVideoListByColumn?id=TOPC1451464665008914&n={}&sort=desc&p={}&mode=0&serviceId=tvcctv&cb=Callback
  tag_url: https://vdn.apps.cntv.cn/api/getHttpVideoInfo.do?pid={}

# 焦点访谈
jdft:
  top_id: TOPC1451558976694518
  home_page: https://tv.cctv.com/lm/jdft/
  day_url: https://api.cntv.cn/NewVideo/getVideoListByColumn?id=TOPC1451558976694518&n={}&sort=desc&p={}&d=&mode=0&serviceId=tvcctv&callback=lanmu_0
  tag_url: https://vdn.apps.cntv.cn/api/getHttpVideoInfo.do?pid={}

# 数据库
mysql:
  url: jdbc:mySql://${web_host}:3306/tbl_news?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
  host: ${web_host}
  port: 3306
  db_name: db_news
  username: ${mysql_username}
  password: ${mysql_password}
mongo:
  host: localhost
  port: 27017
  db_name: db_news
  username: ${mongo_username}
  password: ${mongo_password}
pg:
  host: 47.100.13.100
  port: 5433
  db_name: db1e80de8c3cea427e9c415084bf76160fdb_daily
  username: ${pg_username}
  password: ${pg_password}
  web: https://cloud.memfiredb.com/

wordpress:
  username: ${wordpress_username}
  password: ${wordpress_password}
  posts: http://${web_host}/wp-json/wp/v2/posts
  media: http://${web_host}/wp-json/wp/v2/media


